
title = "Testcases for testing RequestLine Parsing"

[Cases]

[Cases."Valid Request Line"]
description = "Test when Request Line is valid"
request = """\
GET /hello-c-http-server HTTP/1.1\r\n\r\n
"""
expected_response = """
HTTP/1.1 200 OK\r\n\
Content-Type: text/plain\r\n
"""
